List Interface - boolean contains(Object o)
VBSquad/Scrabbling-Java-With-CF pull request #49
Opened 2020-06-25 18:52 UTC by plazzy99

#19 Implement : List Interface - boolean contains(Object o)

Fixes #

#### Checklist:
- [ ] 4 space indentation.
- [ ] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [ ] Sample Input / Output is added at the end of file.
- [ ] Logic Documentation (Comments).
- [ ] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

Keep Contributing. Keep Learning!

2020-06-29 18:37 UTC, jyotijauhari approved these changes

2020-06-29 18:39 UTC, jyotijauhari requested changes
rename word boolen with boolean in file name boolen contains(Object o).java .

2020-06-29 19:05 UTC, plazzy99 commented
@JyotiJauhari changes done

2020-06-30 09:00 UTC, jyotijauhari approved these changes

2020-06-30 09:00 UTC, merged