List Interface - int lastIndexOf(Object o)
VBSquad/Scrabbling-Java-With-CF pull request #50
Opened 2020-06-26 18:37 UTC by plazzy99

#16 Implement : List Interface - int lastIndexOf(Object o)

Fixes #

#### Checklist:
- [ ] 4 space indentation.
- [ ] Coding conventions are followed.
- [ ] Input is taken dynamically.
- [ ] Sample Input / Output is added at the end of file.
- [ ] Logic Documentation (Comments).
- [ ] File names are correct.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

#### Changes proposed in this pull request:
- 
- 

#### Languages Used:
- 
- 

#### Files Added:
- 
- 

> We're happy to help you get this ready -- don't be afraid to ask for help.

Thanks!

Keep Contributing. Keep Learning!

2020-06-29 18:46 UTC, jyotijauhari requested changes
do the changes asked.

2020-06-29 18:46 UTC, JyotiJauhari commented on Collection Interfaces/List Interface/ListLastIndexOf/LastIndexOf ( Object o ).java
> +*/
blank line at the end

2020-06-29 18:46 UTC, JyotiJauhari commented on Collection Interfaces/List Interface/ListLastIndexOf/LastIndexOf ( Object o ).java
> +Initial List : [1, 2, 3, 4, 5]
Initial list written is wrong . do the necessary changes

2020-06-29 18:46 UTC, JyotiJauhari commented on Collection Interfaces/List Interface/ListLastIndexOf/LastIndexOf ( Object o ).java
> +Initial List : [1, 2, 3, 4, 5]
changes in Initial List : [1, 2, 3, 4, 5]

2020-06-29 18:46 UTC, JyotiJauhari commented on Collection Interfaces/List Interface/ListLastIndexOf/LastIndexOf ( Object o ).java
> +LastIndex of 2 in list : -1
changes (we r finding 6 not 2)

2020-06-29 18:46 UTC, JyotiJauhari commented on Collection Interfaces/List Interface/ListLastIndexOf/LastIndexOf ( Object o ).java
> +*/
@plazzy99

2020-06-29 19:07 UTC, plazzy99 commented on Collection Interfaces/List Interface/ListLastIndexOf/LastIndexOf ( Object o ).java
> +*/
done

2020-06-29 19:08 UTC, plazzy99 commented on Collection Interfaces/List Interface/ListLastIndexOf/LastIndexOf ( Object o ).java
> +LastIndex of 2 in list : -1
done

2020-06-29 19:09 UTC, plazzy99 commented
@JyotiJauhari changes done

2020-06-30 16:03 UTC, Dhruv-194 approved these changes
Changes have been done as per the request

2020-06-30 16:03 UTC, merged